spring:
  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.paymentservice.entity.Payment"
        "[spring.json.trusted.packages]": "edu.miu.paymentservice"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"

  main:
    allow-bean-definition-overriding: true

kafka:
  topic:
    payment: "PAYMENT_TOPIC"
    paypal: "PAYPAL_TOPIC"
    credit: "CREDIT_TOPIC"
    bank: "BANK_TOPIC"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
  main:
    allow-bean-definition-overriding: ${SPRING_ALLOW_BEAN_DEFINITION_OVERRIDING}
  zipkin:
    baseUrl: ${ZIPKIN_SERVER}
    service:
      name: ${ZIPKIN_PAYMENT_SERVICE}
kafka:
  topic:
    payment: ${PAYMENT_REQUEST_TOPIC}
    paypal: ${PAYMENT_PAYPAL_TOPIC}
    credit: ${PAYMENT_CREDIT_TOPIC}
    bank: ${BANK_REQUEST_TOPIC}
