apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30086
  selector:
    app: payment-service
  type: NodePort


