apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30086
  selector:
    app: payment-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: anhnt5/payment-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: PAYPAL_TOPIC
              valueFrom:
                service-configmap:
                  name: paypal-service
                  key: paypal-service-topic
            - name: BANK_TOPIC
              valueFrom:
                service-configmap:
                  name: bank-service
                  key: bank-service-topic
            - name: CREDIT_TOPIC
              valueFrom:
                configmap:
                  name: credit-service
                  key: credit-service-topic
            - name: PAYMENT_TOPIC
                valueFrom:
                  configmap:
                    name: payment-service
                    key: payment-service-topic
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

